### ISSUE TITLE
add sex

### ISSUE THREAD

**Issue by SuperSpaceMan230** [Exruw/videotest#6]
add sex to the ebsite
![c6f62a4ee9456cc64ae7cef270ceafc4524e7731](https://user-images.githubusercontent.com/61877191/175554729-353ed4ca-35bc-4fb8-8f3f-5c4fa212ace6.png)

**Comment by SuperSpaceMan230** [comment]
![d997232e976b2b0d8b7a1231a1eb2740027462d6](https://user-images.githubusercontent.com/61877191/175567682-1667ea23-6343-4dc9-bf22-f7a04f96e5a0.png)

**Comment by Exruw** [comment]
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

**Comment by ShadeblastHere** [comment]
> Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

bitch
